### ISSUE TITLE
Ignore override value

### ISSUE THREAD

**Issue by tezooka** [konifar/gradle-unused-resources-remover-plugin#19]
Hi, it's a great tool!

My project has several override values, but it removed.

My proposal is that when used 'tools:override="true"' ignore from remover.
What do you think about this?

Thanks.

**Comment by konifar** [comment]
@tezooka Thanks for you report!
Actually I didn't know `'tools:override="true"` attribute.
Can you tell me the element which is removed like this?

**Comment by konifar** [comment]
Understood! Thanks!
I think your suggestion is good. Let me consider and fix it 🙏

**Comment by tezooka** [comment]
Thank you!!!

**Comment by konifar** [comment]
@tezooka Hi, I fixed this issue in https://github.com/konifar/gradle-unused-resources-remover-plugin/pull/20
and released v0.3.2 just now. Please try it! Thanks

**Comment by tezooka** [comment]
@konifar 
I tried new update and it runed properly!!!
Thank you for your quick and polite response!
