### ISSUE TITLE
wrong modify when use format and type

### ISSUE THREAD

**Issue by takahirom** [konifar/gradle-unused-resources-remover-plugin#21]
Thank you for good plugin! 🎉 
Sorry for not PR.🙇 
I tried to run and there were some problems. 
This resource has been deleted.

module/src/main/res/values-port/floats.xml

```xml
<item name="string_resource_example" format="float" type="string">1.2</item>
```

```java
context.resources.getString(R.string.string_resource_example).toFloat()
```

**Comment by konifar** [comment]
Thanks for reporting!
I found the reason... I thought float is used as `dimen`.
https://github.com/DroidKaigi/conference-app-2018/blob/master/app/src/main/res/values/floats.xml#L3

So let me consider how to solve this 🙏

**Comment by konifar** [comment]
I'll stop to support `floats.xml` because there are several way to define like `type="string"` and `type="integer"`. It's so hard to prepare default `Remover` class.

So if you want to check `floats.xml`, please add custom setting to build.gradle.

```build.gradle
unusedResourcesRemover {
    extraRemovers = [
            createXmlValueRemover("float", "string", "item")
    ]
}
```
