### ISSUE TITLE
The resource specified by manifestPlaceholders is deleted

### ISSUE THREAD

**Issue by komatatsu** [konifar/gradle-unused-resources-remover-plugin#22]
If resources are being referenced using manifestPlaceholders in build.gradle, that resource will be deleted.

Example:
```
productFlavors {
    dev {
        manifestPlaceholders = [
                app_icon      : "@mipmap/ic_launcher_dev",
                app_icon_round: "@mipmap/ic_launcher_dev_round"
        ]
    }
```

In this case, `ic_launcher_dev` and `ic_launcher_dev_round` will be deleted if it is not referenced from other than build.gradle.

I think that it is better not to delete, so I'd like to improve it, but I will keep it an issue for now.

**Comment by konifar** [comment]
Thanks for your report! Understood. I'll fix it. or always welcome your contribution 😉
