### ISSUE TITLE
[FR]React Native Support

### ISSUE THREAD

**Issue by hotchemi** [konifar/gradle-unused-resources-remover-plugin#30]
Thank you for your great plugin!

# Overview

We're using React Native as a hybrid style and we found that the image which is referenced from Javascript layer being removed after executing the plugin task.
I know it's kind of hard with current regexp pattern implementation but this issue is just for heads up and let me try to implement in spare time 😃 

ref: https://facebook.github.io/react-native/docs/images.html#images-from-hybrid-app-s-resources

**Comment by konifar** [comment]
Hi! Thanks for trying this plugin!
I didn't know the way to use the resources from RN project.
I'll check I can support this use case 👀

**Comment by konifar** [comment]
Can you tell me the regex pattern how the resources is used?
Are these enough?

`.*'resource_name'}}.*`
`.*'asset:/resource_name.*

**Comment by hotchemi** [comment]
Thx for the quick reply!
Actually, the document is incorrect..😂 We don't need asset prefix..
I'll dig into source and try to find a way to deal with💪

**Comment by hotchemi** [comment]
Sorry for the late. right now we're using `excludeNames` option and tuned out that's enough for now 😃 Let me close the issue.
