### ISSUE TITLE
Memory caching and speed up 🚤 

### ISSUE THREAD

**Issue by sys1yagi** [konifar/gradle-unused-resources-remover-plugin#9]
Hi, it's a great tool! But in my project it took 25 minutes to run. :dizzy_face:

I think `moduleSrcDirs` files text data can memory caching.

https://github.com/konifar/gradle-unused-resources-remover-plugin/blob/master/plugin/src/main/groovy/com/github/konifar/gradle/remover/remover/AbstractRemover.groovy#L87 🤔 

thanks.

**Comment by konifar** [comment]
Thanks for trying this tool!
I agree with your opinion.
